wal_segment_size: 20
memtable_size: 20
memtable_structure: skiplist
btree_min: 3
btree_max: 5
skiplist_levels: 32
summary_count: 3
cache_size: 10
lsm_levels: 4
sstable_files: "one"
lsm_max_per_level: 4
sstable_size: 10
req_per_time: 60
time_unit: "minute" # possible values "second", "minute", "day"
lsm_leveled_compaction_cfg:
  - 4
  - 10
  - 100
# add more things as they come up to your mind
